title: Kai-Sheng's Blog
#description: Cayman Blog Theme is a clean, responsive blogging theme for Jekyll and Gitlab/GitHub Pages.
show_downloads: true

#baseurl: "/cayman-blog" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://kaisheng714.github.io" # change this to the base hostname & protocol for your site

google_analytics:

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: Kai-Sheng
image: /assets/image/site-image-small.png?date=1108
description: 邁向高品質程式碼
twitter:
  username: kaisheng714

plugins:
  - jekyll-target-blank
  - jekyll-sitemap

target-blank:
    rel: nofollow

 
